services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  acountsdb:
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "miladsade96/configserver:s9"
    container_name: configserver-ms
    hostname: configserver
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "miladsade96/eurekaserver:s9"
    container_name: eurekaserver-ms
    hostname: eurekaserver
    ports:
      - "8072:8072"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  gatewayserver:
    image: "miladsade96/gatewayserver:s9"
    container_name: gateway-ms
    hostname: gatewayserver
    ports:
      - "8073:8073"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      EUREKA_INSTANCE_HOSTNAME: "gatewayserver"
      EUREKA_INSTANCE_PREFERIPADDRESS: "false"
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_INITIAL_DELAY: "60000"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  accounts:
    image: "miladsade96/accounts:s9"
    container_name: accounts-ms
    hostname: accounts
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      acountsdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://acountsdb:3306/accountsdb"
      EUREKA_INSTANCE_HOSTNAME: "accounts"
      EUREKA_INSTANCE_PREFERIPADDRESS: "false"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans:
    image: "miladsade96/loans:s9"
    container_name: loans-ms
    hostname: loans
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      EUREKA_INSTANCE_HOSTNAME: "loans"
      EUREKA_INSTANCE_PREFERIPADDRESS: "false"
      EUREKA_INSTANCE_INSTANCE-ID: "loans:8090"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  loans1:
    image: "miladsade96/loans:s9"
    container_name: loans-ms1
    hostname: loans
    ports:
      - "8091:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      EUREKA_INSTANCE_HOSTNAME: "loans"
      EUREKA_INSTANCE_PREFERIPADDRESS: "false"
      EUREKA_INSTANCE_INSTANCE-ID: "loans:8091"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  cards:
    image: "miladsade96/cards:s9"
    container_name: cards-ms
    hostname: cards
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
      EUREKA_INSTANCE_HOSTNAME: "cards"
      EUREKA_INSTANCE_PREFERIPADDRESS: "false"
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

networks:
  default:
    driver: "bridge"
